export interface DayAvailability {
  day: number; // 0 = Maandag, 1 = Dinsdag, ..., 6 = Zondag
  status: 'available' | 'unavailable' | 'preferred';
  notes?: string;
  startTime?: string;
  endTime?: string;
}

export interface EmployeeAvailability {
  id: string;
  employeeId: string;
  weekNumber: number;
  days: DayAvailability[];
}

export type Department = 'zaal' | 'keuken';
export type EmployeeStatuut = 'Student' | 'Flexi' | 'Vast' | 'Extra';
export type ExperienceLevel = 'Beginner' | 'Gemiddeld' | 'Ervaren' | 'Verantwoordelijke';

export type RecurringFrequency = 'every_week' | 'even_weeks' | 'odd_weeks';

export interface RecurringShiftPreference {
  day: number; // 0 = Maandag, ..., 6 = Zondag
  status: 'available' | 'preferred' | 'unavailable';
  startTime?: string;
  endTime?: string;
  notes?: string;
}

export interface RecurringAvailability {
  frequency: RecurringFrequency; // 'every_week' | 'even_weeks' | 'odd_weeks'
  days: RecurringShiftPreference[];
  active: boolean;
  notes?: string;
  updatedAt?: number;
}

export interface Employee {
  id: string;
  name: string;
  department: Department;
  statuut: EmployeeStatuut;
  experience: ExperienceLevel;
  role?: 'beheerder' | 'medewerker';
  contractDaysPerWeek?: number; // e.g. 4 for Pat & Matthias (fulltime 4 dagen regime), 5 for standard Vast
  color: string; // Used for UI backgrounds/borders
  textBgColor: string; // Tailwind background color
  textColor: string; // Tailwind text color
  email: string;
  phone: string;
  avatarUrl?: string; // Base64 data-URL or image URL
  facebookUrl?: string; // Link naar Facebook profiel
  active: boolean;
  firstLoginComplete?: boolean;
  pin?: string; // Persoonlijke 4-cijferige pincode voor personeelslogin (standaard '1234')
  birthDate?: string; // Geboortedatum (YYYY-MM-DD), wettelijk verplicht voor studenten
  recurringAvailability?: RecurringAvailability; // Vaste shiften per week of om de 2 weken (Flexi, Student, Extra)
}

export interface Shift {
  id: string;
  employeeId: string;
  department?: Department; // 'zaal' or 'keuken'
  weekNumber?: number; // e.g. 26, 27 (volgende week), 28, etc. Default: 26
  day: number; // 0 = Maandag, 1 = Dinsdag, ..., 6 = Zondag
  startTime: string;
  endTime: string;
  notes?: string;
  acknowledged: boolean; // Has employee confirmed?
  status: 'published' | 'draft';
  updatedAt: number;
  notifiedViaEmail?: boolean;
  notifiedViaWhatsApp?: boolean;
  isOpenShift?: boolean; // Shift opengesteld voor intekening
  lastReminderSentAt?: number; // Timestamp van laatst verstuurde shift-herinnering
}

export interface WeekMeta {
  weekNumber: number;
  label: string;
  shortLabel: string;
  isCurrent?: boolean;
  isNext?: boolean;
  isUpcoming?: boolean;
  isArchived?: boolean;
  dateRange: string;
  daysFormatted: string[];
  dayDates?: string[];
  dayDatesFull?: string[];
}

export interface NoticeComment {
  id: string;
  authorId: string;
  authorName: string;
  authorRole?: 'beheerder' | 'medewerker';
  content: string;
  createdAt: number;
}

export interface Notice {
  id: string;
  title: string;
  content: string;
  date: string;
  category: 'planning' | 'wijziging' | 'belangrijk' | 'algemeen';
  author: string;
  targetEmployeeId?: string; // Optioneel gericht aan specifieke medewerker
  shiftId?: string; // Gekoppelde shift voor directe context
  comments?: NoticeComment[];
  reactions?: { [emoji: string]: string[] }; // emoji -> array of employeeIds who reacted
}

export interface SwapCandidate {
  employeeId: string;
  employeeName: string;
  signedUpAt: number;
  note?: string;
}

export interface SwapRequest {
  id: string;
  shiftId: string;
  requesterId: string; // 'beheerder' of id van aanvrager
  reason: string;
  targetEmployeeId?: string; // Optional specific target
  status: 'pending' | 'approved' | 'geweigerd';
  date: string;
  isOpenShift?: boolean; // Opengesteld door beheerder zodat kandidaten kunnen intekenen
  candidates?: SwapCandidate[]; // Medewerkers die hierop hebben ingetekend
}

export interface ChangeLog {
  id: string;
  timestamp: number;
  user: string;
  action: string;
  details: string;
}

export interface AvailabilitySubmissionBackup {
  id: string;
  employeeId: string;
  employeeName: string;
  department: Department;
  weekNumber: number;
  submittedAt: number;
  formattedDate: string;
  days: DayAvailability[];
  notes?: string;
  source?: 'google_forms' | 'staff_portal' | 'manual' | 'excel';
}

export interface ScheduleBackup {
  id: string;
  weekNumber: number;
  createdAt: number;
  formattedDate: string;
  createdBy: string;
  versionTitle: string;
  shiftsCount: number;
  publishedCount: number;
  draftCount: number;
  shifts: Shift[];
  notes?: string;
  autoGenerated?: boolean;
}

export interface AppSettings {
  availabilitySubmissionEnabled: boolean; // Manager can turn on/off availability submission by staff globally
  lockedWeeks?: number[]; // Explicit list of locked week numbers (e.g. [38, 39, 40]) configurable week-by-week
  availabilityLockMessage?: string; // Custom message when locked
  updatedAt?: number;
  updatedBy?: string;
}
